name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: self-hosted
    container:
      image: php:8.3
      options: --memory=50m --memory-swap=50m

    env:
      APP_ENV: testing
      DB_CONNECTION: mariadb
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: email_testing
      DB_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      DEV_TOKEN: ${{ secrets.DEV_TOKEN }}

    name: Run tests on PHP 8.3
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Ensure test database exists
        run: |
          mysql --version
          mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USERNAME" -p"$DB_PASSWORD" \
            -e "CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Show effective testing env
        run: |
          echo "Using DB_CONNECTION=$DB_CONNECTION on $DB_HOST:$DB_PORT/$DB_DATABASE"
          php -r "echo 'pdo_mysql: '.(extension_loaded('pdo_mysql')?'yes':'no').PHP_EOL;"

      - name: Execute tests
        run: |
          php artisan migrate --force
          php artisan test