name: Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  tests:
    runs-on: self-hosted
    env:
      APP_ENV: testing
      DB_CONNECTION: mariadb
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_DATABASE: email_testing
      DB_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      DB_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      DEV_TOKEN: ${{ secrets.DEV_TOKEN }}

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3, 8.4]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, pdo_mysql
          coverage: none

      - name: Ensure test database exists
        run: |
          mysql --version
          mysql -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USERNAME" -p"$DB_PASSWORD" \
            -e "CREATE DATABASE IF NOT EXISTS \`$DB_DATABASE\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Show effective testing env
        run: |
          echo "Using DB_CONNECTION=$DB_CONNECTION on $DB_HOST:$DB_PORT/$DB_DATABASE"
          php -r "echo 'pdo_mysql: '.(extension_loaded('pdo_mysql')?'yes':'no').PHP_EOL;"

      - name: Execute tests
        run: php artisan test
